%Navigate to folder where the data is located. Copy and past each statement
%into the command window and run them one at a time.

tableTrain = featureExtractionTrainFileWise(...
    'Edited Jumping Jacks NON_DOMINATE_WRIST Jul 26, 2015 63120 PM.csv', ...
    'Edited Pushups NON_DOMINATE_WRIST Jul 26, 2015 55445 PM.csv', ...
    'Edited Situps NON_DOMINATE_WRIST Jul 26, 2015 55725 PM.csv', ...
    'Edited Desk Work NON_DOMINANT_WRIST Aug 5, 2015 11_43_48 AM.csv', ...
    'Edited Staying Still (Hand on Desk) NON_DOMINANT_WRIST Aug 5, 2015 113711 AM.csv', ...
    'Edited Staying Still (Standing with Hands on Sides) NON_DOMINANT_WRIST Aug 5, 2015 11_41_34 AM.csv', ...
    'Edited Walking NON_DOMINANT_WRIST Aug 5, 2015 11_58_10 AM.csv', ...
    'Edited Jogging NON_DOMINANT_WRIST Aug 5, 2015 12_02_20 PM.csv');

%Import tableTrain, train a model, name your model 'trainedClassifier'
classificationLearner;

%The following statement will create a visualization of the tree (assuming
%a decisoin tree classifier is used)
view(trainedClassifier, 'Mode', 'graph');

tableTest1 = featureExtractionTestFileWise('Test Sophia Situps.csv');
tableTest2 = featureExtractionTestFileWise('Test Sophia Jumping Jacks with Pauses.csv');

tablePredict1 = predict(trainedClassifier, tableTest1{:,trainedClassifier.PredictorNames});
tablePredict2 = predict(trainedClassifier, tableTest2{:,trainedClassifier.PredictorNames});

