%Navigate to folder where the data is located. Copy and past each statement
%into the command window and run them one at a time.

tableTrain = featureExtractionTrainFileWise(...
    'Edited Jumping Jacks NON_DOMINATE_WRIST Jul 26, 2015 63120 PM.csv', ...
    'Edited Pushups NON_DOMINATE_WRIST Jul 26, 2015 55445 PM.csv', ...
    'Edited Situps NON_DOMINATE_WRIST Jul 26, 2015 55725 PM.csv', ...
    'Edited Desk Work NON_DOMINANT_WRIST Aug 5, 2015 11_43_48 AM.csv', ...
    'Edited Staying Still (Hand on Desk) NON_DOMINANT_WRIST Aug 5, 2015 113711 AM.csv', ...
    'Edited Staying Still (Standing with Hands on Sides) NON_DOMINANT_WRIST Aug 5, 2015 11_41_34 AM.csv', ...
    'Edited Walking NON_DOMINANT_WRIST Aug 5, 2015 11_58_10 AM.csv', ...
    'Edited Jogging NON_DOMINANT_WRIST Aug 5, 2015 12_02_20 PM.csv');

%Import tableTrain, train a model, name your model 'trainedClassifier'
classificationLearner;

tableTest = featureExtractionTestFileWise('Test Sophia Situps Data.csv');

tablePredict = predict(trainedClassifier, tableTest{:,trainedClassifier.PredictorNames});

tableEvaluate = [tableTest tablePredict];

